### ISSUE TITLE
Build hangs at 'Skipping 'AzureWebJobsStorage' from local settings as it's already defined in current environment variables.' and then fails.

### ISSUE THREAD

**Issue by fperreaultnv** [julienblin/uno-serverless#33]
λ npm run start

> pineapple@0.1.0 start C:\Src\pineapple\api
> webpack --env=development --watch

Starting type checking service...
Using 1 worker with 2048MB memory limit

webpack is watching the files…

(node:11044) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Executing post-build scripts
No type errors found
Version: typescript 2.9.2
Time: 2919ms
Hash: 0cc959441a8c78cbb4be
Version: webpack 4.16.1
Time: 22289ms
Built at: 07/24/2018 5:56:13 PM
                        Asset       Size           Chunks             Chunk Names
                 proxies.json   1.02 KiB                   [emitted]
              health/index.js   23.1 MiB           health  [emitted]  health
          newsletter/index.js   23.1 MiB       newsletter  [emitted]  newsletter
               oauth/index.js   23.1 MiB            oauth  [emitted]  oauth
             openapi/index.js   23.1 MiB          openapi  [emitted]  openapi
     password-resets/index.js   23.1 MiB  password-resets  [emitted]  password-resets
            register/index.js   23.1 MiB         register  [emitted]  register
                sync/index.js   23.1 MiB             sync  [emitted]  sync
               users/index.js   23.1 MiB            users  [emitted]  users
                    host.json    8 bytes                   [emitted]
          local.settings.json   4.38 KiB                   [emitted]
         master-data/index.js   23.1 MiB      master-data  [emitted]  master-data
         health/function.json  295 bytes                   [emitted]
    master-data/function.json  300 bytes                   [emitted]
     newsletter/function.json  279 bytes                   [emitted]
        openapi/function.json  301 bytes                   [emitted]
          oauth/function.json  301 bytes                   [emitted]
password-resets/function.json  284 bytes                   [emitted]
           sync/function.json  273 bytes                   [emitted]
       register/function.json  295 bytes                   [emitted]
          users/function.json  246 bytes                   [emitted]
templates/password-reset.html   12.3 KiB                   [emitted]
                 openapi.json   25.4 KiB                   [emitted]
[./src/config.ts] 1.45 KiB {health} {master-data} {newsletter} {oauth} {openapi} {password-resets} {register} {sync} {users} [built]
[./src/handlers/common.ts] 5.96 KiB {health} {master-data} {newsletter} {oauth} {openapi} {password-resets} {register} {sync} {users} [built]
[./src/handlers/health.ts] 432 bytes {health} [built]
[./src/handlers/master-data.ts] 411 bytes {master-data} [built]
[./src/handlers/newsletter.ts] 2.08 KiB {newsletter} [built]
[./src/handlers/oauth.ts] 1.36 KiB {oauth} [built]
[./src/handlers/openapi.ts] 947 bytes {openapi} [built]
[./src/handlers/password-resets.ts] 2.06 KiB {password-resets} [built]
[./src/handlers/register.ts] 1.25 KiB {register} [built]
[./src/handlers/sync.ts] 1.1 KiB {sync} [built]
[./src/handlers/users.ts] 1.07 KiB {users} [built]
[./src/services/auth.service.ts] 4.78 KiB {health} {master-data} {newsletter} {oauth} {openapi} {password-resets} {register} {sync} {users} [built]
[./src/services/contentful-sync.service.ts] 6.53 KiB {health} {master-data} {newsletter} {oauth} {openapi} {password-resets} {register} {sync} {users} [built]
[./src/services/entities.ts] 1.77 KiB {health} {master-data} {newsletter} {oauth} {openapi} {password-resets} {register} {sync} {users} [built]
[fs] external "fs" 42 bytes {health} {master-data} {newsletter} {oauth} {openapi} {password-resets} {register} {sync} {users} [built]
    + 1102 hidden modules

WARNING in ./node_modules/ms-rest/lib/serviceClient.js 441:19-43
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ms-rest/lib/msRest.js
 @ ./node_modules/ms-rest-azure/lib/msRestAzure.js
 @ ./node_modules/uno-serverless-azure/dist/index.js
 @ ./src/handlers/common.ts
 @ ./src/handlers/master-data.ts

WARNING in ./node_modules/handlebars/lib/index.js 22:38-56
require.extensions is not supported by webpack. Use a loader instead.
 @ ./node_modules/uno-serverless-handlebars/dist/index.js 1:2988-3009
 @ ./src/handlers/common.ts
 @ ./src/handlers/master-data.ts

WARNING in ./node_modules/handlebars/lib/index.js 23:2-20
require.extensions is not supported by webpack. Use a loader instead.
 @ ./node_modules/uno-serverless-handlebars/dist/index.js 1:2988-3009
 @ ./src/handlers/common.ts
 @ ./src/handlers/master-data.ts

WARNING in ./node_modules/handlebars/lib/index.js 24:2-20
require.extensions is not supported by webpack. Use a loader instead.
 @ ./node_modules/uno-serverless-handlebars/dist/index.js 1:2988-3009
 @ ./src/handlers/common.ts
 @ ./src/handlers/master-data.ts

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Skipping 'AzureWebJobsStorage' from local settings as it's already defined in current environment variables.
Function host is not running.
Application is shutting down...
Terminate batch job (Y/N)? Y

**Comment by fperreaultnv** [comment]
Terminating batch job + restarting start script usually fixes the issue, until it comes back.

**Comment by julienblin** [comment]
Should be fixed by Webpack SpawnPlugin + enhancements on azure functions core tools.
