### ISSUE TITLE
parseBodyAsFORM + validateBody with schema containing boolean property fails to validate properly

### ISSUE THREAD

**Issue by fperreaultnv** [julienblin/uno-serverless#34]
`const oauthTokenRequestSchema: JSONSchema = {`
  additionalProperties: false,
  properties: {
    {...}
    subscribeToNewsletter: {
      type: "boolean",
    }
  },
  type: "object",
};

export const handler = httpFunc()
  .use(parseBodyAsFORM())
  .use(validateBody(oauthTokenRequestSchema))
  .handler(http<Container>(
    async ({ event, services: { authService }}) => {
...
    }));`

Body is not validated when sending _false_ in the property _subscribeToNewsletter_ as x-www-form-urlencoded.

**Comment by julienblin** [comment]
This is because parsing the form always returns attributes as string.

Possible solution for validation:
```javascript
const oauthTokenRequestSchema: JSONSchema = {
  additionalProperties: false,
  properties: {
    subscribeToNewsletter: {
    type: "string",
    enum: [ "true", "false" ]
  }
},
type: "object",
};
```
