### ISSUE TITLE
Making a request with a header without a value results in an authentication error

### ISSUE THREAD

**Issue by fperreaultnv** [julienblin/uno-serverless#69]
Here are some fiddler traces of two exactly identical calls, with the only difference that the second one sends an **empty** Accept-Language header. The handler uses the `principalFromBearerToken` middleware.

## Expected Behavior
Both calls are handled the same way regarding authentication

## Current Behavior
Both calls do not react the same way.

### Fiddler trace 1 : Accept-Language=fr-CA

GET http://localhost:7071/api/content/events/49m3lu2J9CKoKUcMgAQ4yO HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJkMjFiNTE0OTMxNjc4NDU0YWM2YzM4YTVmYjRiZWUwIn0.eyJzdWIiOiI5MzdlMjQ5Y2I4MDYwYzRlNmFkODFjOGEiLCJpYXQiOjE1MzU2NjYxMzYsImV4cCI6MTUzNTY2OTczNn0.w1f_VsoGSjL9aAQ7O6ZrmrxMsrOyffwJQvg0sLfiA-34ZAnnTz4w3PiRCr0gQxxN_2zKS2zEgbagptyz3oKl7s12RYt6P1nTd8tWW65w5QKpMt03HS0JrDn2k9Svm5Pun3EQec5eRuHZ20DBwhcyh_Y4b_kN70jxFkPSqDWJXmEtys7KKxbHTZ_Oofzbb1uiYxST3FDON4z8d-xDkElfF6XI_UhPelYmquGBfkz9ZlBrOC4ju5Eoi26whfA2JfrqJ4IuXrWhRBHwS9eXy5G6hzo1QBbydnsntsauBn26JT8LhHQoAKVgzWT81U6Lq13fVJlCJ0W0n-VMQ7sTLDu_jg
Accept-Language: fr-CA
User-Agent: PostmanRuntime/7.2.0
Accept: */*
Host: localhost:7071
accept-encoding: gzip, deflate
Connection: keep-alive

HTTP/1.1 200 OK
Date: Thu, 30 Aug 2018 22:03:51 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

2f8
{"name":"Sports @ Centre Bell","description":"Description de l'événement.","categoryId":"1bmVSWowz0Q2e6kQeOgwqm","isSpecial":false,"isAllDay":true,"ticketsUrl":"https://localhost:7071/api/content/events/49m3lu2J9CKoKUcMgAQ4yO/partner-redirect","accessType":"freeWalkIn","date":"2018-08-30T11:27:40.922Z","dateType":"Sports","altDate":"2018-08-30T12:27:40.988Z","altDateType":"Alt-FR","isReducedPrice":false,"id":"49m3lu2J9CKoKUcMgAQ4yO","images":["http://images.ctfassets.net/sl3u2k27mhhy/6olZ7PP2P6eOWSqi4W8KeW/316fc5a36e810214f8820744cd960d06/ttt.jpg"],"isPast":false,"venue":{"name":"Centre Bell","location":{"lon":-73.56947839999998,"lat":45.49603},"address":"1909 Avenue des Canadiens-de-Montréal, Montréal, QC H4B 5G0","id":"3893SwMEmQiC6UCkE8K0a6"}}
0

### Fiddler trace 2: Accept-Language=
GET http://localhost:7071/api/content/events/49m3lu2J9CKoKUcMgAQ4yO HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJkMjFiNTE0OTMxNjc4NDU0YWM2YzM4YTVmYjRiZWUwIn0.eyJzdWIiOiI5MzdlMjQ5Y2I4MDYwYzRlNmFkODFjOGEiLCJpYXQiOjE1MzU2NjYxMzYsImV4cCI6MTUzNTY2OTczNn0.w1f_VsoGSjL9aAQ7O6ZrmrxMsrOyffwJQvg0sLfiA-34ZAnnTz4w3PiRCr0gQxxN_2zKS2zEgbagptyz3oKl7s12RYt6P1nTd8tWW65w5QKpMt03HS0JrDn2k9Svm5Pun3EQec5eRuHZ20DBwhcyh_Y4b_kN70jxFkPSqDWJXmEtys7KKxbHTZ_Oofzbb1uiYxST3FDON4z8d-xDkElfF6XI_UhPelYmquGBfkz9ZlBrOC4ju5Eoi26whfA2JfrqJ4IuXrWhRBHwS9eXy5G6hzo1QBbydnsntsauBn26JT8LhHQoAKVgzWT81U6Lq13fVJlCJ0W0n-VMQ7sTLDu_jg
Accept-Language: 
User-Agent: PostmanRuntime/7.2.0
Accept: */*
Host: localhost:7071
accept-encoding: gzip, deflate
Connection: keep-alive

HTTP/1.1 401 Unauthorized
Date: Thu, 30 Aug 2018 22:07:06 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Content-Length: 108

{"error":{"code":"unauthorized","target":"authorization header","message":"No authorization header found."}}

**Comment by julienblin** [comment]
This is due to a bug in azure functions runtime parsing.
Not a lot that can be done here...
